# The Nigerian Ledger by Dabira Awoniyi - Jekyll Configuration

title: "The Nigerian Ledger by Dabira Awoniyi"
tagline: "Unmasking Deception, Challenging the System, One Entry at a Time."
description: >-
  An investigative blog exploring fraud, forensic accounting, and systemic issues in Nigeria.

# Site URL (Update this if you're using GitHub Pages)
url: "https://thenigerianledger.github.io"
baseurl: "" # Leave this empty unless you have a subdirectory

# Timezone
timezone: Africa/Lagos

# Theme
theme_mode: dark # Dark theme with magenta (customizable in CSS)

# Social Media Links (Replace with your actual links)
github:
  username: dabiraawoniyi

twitter:
  username: your_twitter_handle

social:
  name: Dabira Awoniyi
  email: your_email@example.com
  links:
    - https://twitter.com/your_twitter_handle
    - https://github.com/dabiraawoniyi
    - https://www.linkedin.com/in/your-linkedin/

# Navigation (Modify as needed)
navigation:
  - title: "Home"
    url: "/"
  - title: "Fraud Archives"
    url: "/categories/fraud-archives/"
  - title: "Numbers Don’t Lie: The Audit Trail"
    url: "/categories/numbers-dont-lie/"
  - title: "Discourse Hub"
    url: "/categories/discourse-hub/"
  - title: "About"
    url: "/about/"

# Blog Sections (Categories & Tags)
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# Comments (Choose one: Utterances or Disqus)
comments:
  provider: utterances
  utterances:
    repo: dabiraawoniyi/nigerian-ledger-comments
    issue_term: title

# Google Analytics (Optional)
analytics:
  google:
    id: G-XXXXXXXXXX # Replace with your actual tracking ID

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
